import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'
import '../styles/globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const prompt = Prompt({ weight:['100','200','300','400','500','600','700','800','900'], style:['italic','normal'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Wuhan Lab',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${prompt.className} relative`}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
